import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")
DB_PATH = os.getenv("DB_PATH", "users.db")

IRON_MINING_INTERVAL = int(os.getenv("IRON_MINING_INTERVAL", "600"))
SILVER_MINING_INTERVAL = int(os.getenv("SILVER_MINING_INTERVAL", "1200"))

IRON_SELL_PRICE = int(os.getenv("IRON_SELL_PRICE", "10"))
SILVER_SELL_PRICE = int(os.getenv("SILVER_SELL_PRICE", "20"))

DAILY_REWARD_COINS = int(os.getenv("DAILY_REWARD_COINS", "500"))
DAILY_REWARD_INTERVAL = int(os.getenv("DAILY_REWARD_INTERVAL", "86400"))

ARMORY_INITIAL_CAPACITY = int(os.getenv("ARMORY_INITIAL_CAPACITY", "5"))
ARMORY_UPGRADE_BASE_PRICE = int(os.getenv("ARMORY_UPGRADE_BASE_PRICE", "500"))
ARMORY_UPGRADE_MULTIPLIER = float(os.getenv("ARMORY_UPGRADE_MULTIPLIER", "1.3"))
ARMORY_CAPACITY_INCREMENT = int(os.getenv("ARMORY_CAPACITY_INCREMENT", "2"))

MINING_LOOP_INTERVAL = int(os.getenv("MINING_LOOP_INTERVAL", "60"))
